name: Push
jobs:
  publish_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn
      - run: yarn build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 'lts/*'
      - run: yarn
      - run: yarn build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
on:
  push:
    branches: [main]
