name: Push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        run: >
          npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH_TOKEN;
          npm publish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
on:
  push:
    branches: [main]
