name: Push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        run: >
          yarn config set npmAuthToken $NPM_AUTH_TOKEN;
          yarn config set registry https://registry.npmjs.org/;
          yarn npm publish --tolerate-republish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
on:
  push:
    branches: [main]
